# docker-compose.yml
version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
     - redisdata:/data
    environment:
     - REDIS_REPLICATION_MODE=master
  database:
    image: "postgres" # use latest official postgres version
    ports:
    - "5433:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
  redisdata:
    driver: local